name: Sync to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Private Repo
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        token: ${{ secrets.PRIVATE_REPO_TOKEN }}
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Filter out folders
      run: |
        git filter-repo --path .github/workflows --invert-paths
        git filter-repo --path tests --invert-paths

    - name: Clone Public Repo
      run: |
        git clone https://github.com/your-org/public-repo.git public-repo
        cd public-repo
        git checkout main

    - name: Sync to Public Repo
      run: |
        rsync -av --exclude='.github/workflows' --exclude='tests' ./ public-repo/
        cd public-repo
        git add .
        git commit -m "Sync changes from private repo"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }}
