name: Sync to Public Repo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Private Repo
      uses: actions/checkout@v2
      with:
        repository: Diabatix/pyColdStreamDev
        token: ${{ secrets.PAT_TOKEN }}
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install git-filter-repo
      run: |
        pip install git-filter-repo

    - name: Filter out .github/workflows folder
      run: |
        git filter-repo --path .github/workflows --invert-paths --force

    - name: Filter out tests folder
      run: |
        git filter-repo --path tests --invert-paths --force

    - name: Get Last Commit Message
      id: get_commit_msg
      run: |
        LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
        CLEAN_COMMIT_MSG=$(echo "$LAST_COMMIT_MSG" | tr -d '\n')
        echo "last_commit_msg=$CLEAN_COMMIT_MSG" >> $GITHUB_ENV

    - name: Clone Public Repo
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git clone https://${{ secrets.PAT_TOKEN }}@github.com/Diabatix/pyColdStream.git public-repo
        cd public-repo
        git checkout main

    - name: Sync to Public Repo
      run: |
        rsync -av --exclude='.git' --exclude='.github/workflows' --exclude='tests' ./ public-repo/
        cd public-repo
        git config user.name "GitHub Action"
        git config user.email "action@github.com"
        git add .
        git commit -m "${{ env.last_commit_msg }}"
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
