name: Sync Changes to Public Repository

on:
  push:
    branches:
      - master  # Trigger the workflow on push to master branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout private repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.PAT_TOKEN }}

    - name: Setup Git
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"

    - name: Copy files to sync
      run: |
        mkdir -p sync
        rsync -av --progress . sync --exclude '.github/workflows' --exclude 'tests'

    - name: Initialize clean repository
      run: |
        cd sync
        git init
        git remote remove origin || true  # Remove existing remote if it exists
        git remote add origin https://github.com/Diabatix/pyColdStream.git
        git add .
        git commit -m "Initial commit with cleaned content"
        git push -u origin main --force
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
